version: 0.2

env:
  variables:
    REPOSITORY_URI: 918565533547.dkr.ecr.us-east-1.amazonaws.com/codebuild-project-winows-docker
    
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - sudo yum install docker-ce docker-ce-cli containerd.io
      - sudo yum install -y yum-utils \
        device-mapper-persistent-data \
        lvm2
      - yum list docker-ce
      - sudo systemctl start docker
  build:
    commands:
      - echo Building the Docker image ... docker build -t $env:REPOSITORY_URI:latest
      - sudo docker run hello-world
  post_build:
    commands:
      - sudo docker images hello-world
      - sudo docker push $env:REPOSITORY_URI:latest




