version: 0.2

env:
  variables:
    REPOSITORY_URI: 918565533547.dkr.ecr.us-east-1.amazonaws.com/codebuild-project-winows-docker
    
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo Building the Docker image ... docker build -t $env:REPOSITORY_URI:latest
      - docker run hello-world
  post_build:
    commands:
      - docker images hello-world
      - docker push $env:REPOSITORY_URI:latest




