FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2016

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
	
# Download the Build Tools bootstrapper.
ADD https://aka.ms/vs/16/release/vs_buildtools.exe C:/TEMP/
RUN Write-Host "Installing vs_buildtools_2019"; \
	Start-Process -Wait -FilePath C:\TEMP\vs_buildtools.exe -ArgumentList '--wait', '--quiet', '--norestart' ,'--includeRecommended', '--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools', '--add Microsoft.VisualStudio.Workload.VCTools'; \
	Remove-Item –path C:/TEMP/ –recurse -force;
